const:
  default-page-size: 20

file:
  directory: D:\khj\2024-02\download\greengram_ver3

jwt:
  issuer: green@green.kr
  secret-key: study-springboot



mybatis:
  mapper-locations:  mappers/**/*.xml

spring:
  application:
    name: GreenGramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size:  60MB


springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
